name: Washizus judgement

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run fmt check
        run: cargo fmt --check
      - name: Run clippy check
        run: cargo clippy -- -D warnings 
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          dry-run: ${{ github.event_name != 'push' }}
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
          ignore-unpublished-changes: true
